# Generated by Django 3.1.7 on 2021-04-02 07:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('course', '0002_student'),
    ]
    operations = [
        migrations.DeleteModel(
            name='student',
        ),
    ]
