# Generated by Django 3.1.7 on 2021-04-09 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_delete_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_master',
            name='fees',
            field=models.IntegerField(default=0),
        ),
    ]
