# Generated by Django 3.1.7 on 2021-05-01 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0004_course_master_fees'),
    ]

    operations = [
        migrations.CreateModel(
            name='inquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inq_id', models.IntegerField(blank=True, default=0, null=0)),
                ('date', models.DateField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=22, null=True)),
                ('second_name', models.CharField(blank=True, max_length=22, null=True)),
                ('state_name', models.CharField(blank=True, max_length=22, null=True)),
                ('area_name', models.CharField(blank=True, max_length=22, null=True)),
                ('city_name', models.CharField(blank=True, max_length=22, null=True)),
                ('mobile_num', models.IntegerField(blank=True, default=0, null=True)),
                ('landline_num', models.IntegerField(blank=True, default=0, null=True)),
                ('education', models.CharField(blank=True, max_length=22, null=True)),
                ('clg_name', models.CharField(blank=True, max_length=22, null=True)),
                ('ref_name', models.CharField(blank=True, max_length=22, null=True)),
                ('remarks', models.CharField(blank=True, max_length=22, null=True)),
                ('inq_held_by', models.CharField(blank=True, max_length=22, null=True)),
                ('inq_num', models.IntegerField(blank=True, default=0, null=True)),
                ('demo_lect_date', models.DateField(blank=True, null=True)),
                ('demo_lect_time', models.TimeField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='inquiry', to='course.course_master')),
            ],
        ),
    ]
