# Generated by Django 3.1.7 on 2021-05-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry_table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='inq_id',
            field=models.IntegerField(blank=True, default=1, null=0),
        ),
    ]
