# Generated by Django 3.1.7 on 2021-05-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry_table', '0003_auto_20210501_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='inq_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
