# Generated by Django 3.1.7 on 2021-05-01 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_master_fees'),
        ('inquiry_table', '0005_auto_20210501_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='course',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inquiry', to='course.course_master'),
        ),
    ]
