# Generated by Django 3.1.7 on 2021-05-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry_table', '0009_remove_inquiry_inq_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='inquiry',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
