# Generated by Django 3.1.7 on 2021-04-11 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admission', '0005_auto_20210411_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt', models.IntegerField()),
                ('Receipt_Date', models.DateField(blank=True, null=True)),
                ('Amount', models.IntegerField()),
                ('payment_type', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque')], max_length=20)),
                ('ch_no', models.IntegerField()),
                ('Bank_Name', models.CharField(max_length=55)),
                ('Branch_Name', models.CharField(max_length=55)),
                ('admission', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='admission', to='admission.admission')),
            ],
        ),
    ]
