# Generated by Django 3.1.7 on 2021-04-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_auto_20210426_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_info',
            name='ch_no',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
