# Generated by Django 3.1.7 on 2021-04-07 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Id', models.IntegerField()),
                ('Date_of_addmission', models.DateField()),
                ('Course_Id', models.IntegerField()),
                ('Addmission_Id', models.IntegerField()),
                ('Start_Time', models.TimeField()),
                ('End_Time', models.TimeField()),
                ('Receipt_Id', models.IntegerField()),
                ('Start_Date', models.DateField()),
                ('End_Date', models.DateField()),
                ('Fees', models.IntegerField()),
                ('Status', models.CharField(max_length=6)),
                ('No_of_Days', models.IntegerField()),
                ('Remarks', models.CharField(max_length=22)),
                ('Pending_fees', models.IntegerField()),
            ],
        ),
    ]
