# Generated by Django 3.1.7 on 2021-04-10 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_auto_20210405_1013'),
        ('course', '0004_course_master_fees'),
    ]

    operations = [
        migrations.CreateModel(
            name='admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_of_addmission', models.DateField(blank=True, null=True)),
                ('Start_Time', models.TimeField()),
                ('End_Time', models.TimeField()),
                ('Start_Date', models.DateField(blank=True, null=True)),
                ('End_Date', models.DateField(blank=True, null=True)),
                ('photo_copy', models.FileField(blank=True, upload_to='media/')),
                ('Fees', models.IntegerField()),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('Deactive', 'Deactive'), ('close', 'close')], max_length=20)),
                ('No_of_Days', models.IntegerField()),
                ('Remarks', models.CharField(max_length=22)),
                ('Pending_fees', models.CharField(max_length=20)),
                ('Course', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admission', to='course.course_master')),
                ('Student', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admission', to='students.student')),
            ],
        ),
    ]
