# Generated by Django 3.1.7 on 2021-04-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='Pending_fees',
            field=models.IntegerField(choices=[('Yes', 'No'), ('Yes', 'No')]),
        ),
    ]
