# Generated by Django 3.1.7 on 2021-04-10 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20210405_1013'),
        ('course', '0004_course_master_fees'),
        ('admission', '0002_auto_20210410_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='Course',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='admission', to='course.course_master'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='Student',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='admission', to='students.student'),
        ),
    ]
