# Generated by Django 3.1.7 on 2021-04-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_auto_20210408_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='Date_of_addmission',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='End_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='Pending_fees',
            field=models.IntegerField(choices=[('Yes', 'Yes'), ('No', 'No')]),
        ),
        migrations.AlterField(
            model_name='admission',
            name='Start_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
