# Generated by Django 3.1.7 on 2021-04-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0003_auto_20210408_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='Pending_fees',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20),
        ),
    ]
