# Generated by Django 3.1.7 on 2021-05-01 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0007_auto_20210501_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='inq_id',
            new_name='inquiry',
        ),
    ]
