# Generated by Django 3.1.7 on 2021-05-01 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry_table', '0004_auto_20210501_1212'),
        ('admission', '0009_auto_20210501_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='inquiry',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='admission', to='inquiry_table.inquiry'),
        ),
    ]
