# Generated by Django 3.1.7 on 2021-05-01 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry_table', '0006_auto_20210501_1214'),
        ('admission', '0011_auto_20210501_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='inquiry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='admission', to='inquiry_table.inquiry'),
        ),
    ]
