# Generated by Django 3.1.7 on 2021-05-01 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0012_auto_20210501_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='inquiry',
        ),
    ]
