# Generated by Django 3.1.7 on 2021-05-01 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry_table', '0007_auto_20210501_1215'),
        ('admission', '0013_remove_admission_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='Inquiry',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='admission', to='inquiry_table.inquiry'),
        ),
    ]
