# Generated by Django 3.1.7 on 2021-05-02 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry_table', '0008_auto_20210501_1604'),
        ('admission', '0015_auto_20210501_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='Inquiry',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='admission', to='inquiry_table.inquiry'),
        ),
    ]
