# Generated by Django 3.1.7 on 2021-05-02 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry_table', '0009_remove_inquiry_inq_id'),
        ('admission', '0017_auto_20210502_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='Inquiry',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='admission', to='inquiry_table.inquiry'),
        ),
    ]
