# Generated by Django 3.1.7 on 2021-05-02 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0018_auto_20210502_0943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='Inquiry',
            new_name='inquiry',
        ),
    ]
